---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    mapping:
      defaults:
        tags:
          - latest
          - '{{ timestamp }}'
        pushSourceContainer: false
      components:
        - name: ${component_name}
          componentTags:
            - 'latest'
          repositories:
            - url: quay.io/hacbs-release-tests/${component_name}
              tags:
                - '{{ git_sha }}'
                - '{{ git_short_sha }}'
                - '{{ digest_sha }}'
                - 'v1.0.0'
                - '{{ oci_version }}'     
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
