---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    jira:
      jiraAdvisorySecret: advisory-jira-secret-${component_name}
    github:
      githubSecret: github-pat-${component_name}
    sign:
      configMapName: hacbs-signing-pipeline-config-redhatrelease2
    mapping:
      components:
        - name: ${component_name}
          files:
            - filename: main_86.15272_linux_amd64.zip
              source: /releases/main_86.15272_linux_amd64.zip
              arch: amd64
              os: linux
    releaseNotes:
      product_id: [01]
      product_name: github-${application_name}
      product_version: ${component_version}
      # shimming the product_stream and cpe that would normally be added by prodsec
      product_stream: github-${application_name}
      cpe: cpe:/a:github:github:${component_version}
    intention: staging
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/release-to-github/release-to-github.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
