---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${managed_sa_name}
  labels:
    originating-tool: "${originating_tool}"
secrets:
  - name: konflux-ci-konflux-release-trusted-artifacts-pull-secret-${component_name}
  - name: push-${component_name}
  - name: registry-redhat-io-quay-token-secret-${component_name}
  - name: konflux-advisory-jira-secret
imagePullSecrets:
  - name: push-${component_name}
  - name: konflux-ci-konflux-release-trusted-artifacts-pull-secret-${component_name}
