---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    fileUpdates:
      - file_updates_secret: managed-tenants-file-updates-stage-secret
        paths:
          - path: addons/test-product/addonimagesets/stage/my-addon.yaml
            seed: 'indexImage: \nname: my-addon\nrelatedImages: []'
            replacements:
              - key: .indexImage
                replacement: >-
                  |indexImage:.*|indexImage: {{ .components[] | 
                  (.repository + "@" + (.containerImage | split ("@"))[-1]) }}|
        repo: 'https://gitlab.cee.redhat.com/rhtap-release/managed-tenants-stage/'
        upstream_repo: 'https://gitlab.cee.redhat.com/rhtap-release/managed-tenants-stage/'
    mapping:
      components:
        - name: ${component_name}
          repositories:
            - url: quay.io/hacbs-release-tests/osd-addons/e2e-component-index
              tags:
                - '{{ git_short_sha }}'
          pushSourceContainer: false
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/push-to-addons-registry/push-to-addons-registry.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
