---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{ source_url }}/-/tree/{{ revision }}'
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "${component_branch}"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ${application_name}
    appstudio.openshift.io/component: ${component_name}
    pipelines.appstudio.openshift.io/type: build
  name: ${component_name}-on-push
  namespace: ${tenant_namespace}
spec:
  params:
    - name: ociStorage
      value: quay.io/redhat-user-workloads-stage/${tenant_namespace}/${component_name}:{{revision}}
    - name: package-name
      value: hello
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: build-architectures
      value: ["x86_64"]
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-{{component_name}}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
