---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${managed_sa_name}
  labels:
    originating-tool: "${originating_tool}"
secrets:
  - name: konflux-ci-konflux-release-trusted-artifacts-pull-secret-${component_name}
  - name: push-${component_name}
  - name: pyxis-${component_name}
  - name: konflux-cosign-signing-stage-${component_name}
  - name: konflux-advisory-jira-secret
  - name: publish-to-cgw-secret
imagePullSecrets:
  - name: push-${component_name}
  - name: konflux-ci-konflux-release-trusted-artifacts-pull-secret-${component_name}
