---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-signing-pipeline
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton pipeline for simple signing. It is meant to be used by the rh-sign-image task, not as a standalone managed
    pipeline.
  params:
    - name: pipeline_image
      description: An image with CLI tools needed for the signing
      default: quay.io/redhat-isv/operator-pipelines-images:released
      type: string
    - name: manifest_digests
      description: Space separated manifest digest for the signed content, usually in the format sha256:xxx
      type: string
    - name: references
      description: >-
        Space separated docker reference for the signed content,
        e.g. registry.redhat.io/redhat/community-operator-index:v4.9
      type: string
    - name: repositories
      description: >-
        Space separated list of repository names where the signed content is located,
        e.g. redhat-community-operator-index
      type: string
    - name: requester
      description: Name of the user that requested the signing, for auditing purposes
      type: string
    - name: config_map_name
      description: A config map name with configuration
      default: hacbs-signing-pipeline-config
      type: string
    - name: taskGitUrl
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
      type: string
    - name: taskGitRevision
      description: The revision in the taskGitUrl repo to be used
      type: string
    - name: pyxisServer
      type: string
      description: The server type to use. Options are 'production','production-internal,'stage-internal' and 'stage'
      default: production
  workspaces:
    - name: pipeline
  tasks:
    - name: collect-simple-signing-params
      retries: 5
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/collect-simple-signing-params/collect-simple-signing-params.yaml
      params:
        - name: config_map_name
          value: $(params.config_map_name)
    - name: request-and-upload-signature
      retries: 5
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml
      params:
        - name: manifest_digests
          value: $(params.manifest_digests)
        - name: references
          value: $(params.references)
        - name: repositories
          value: $(params.repositories)
        - name: requester
          value: $(params.requester)
        - name: sig_key_names
          value: $(tasks.collect-simple-signing-params.results.sig_key_names)
        - name: umb_ssl_cert_secret_name
          value: $(tasks.collect-simple-signing-params.results.umb_ssl_cert_secret_name)
        - name: umb_ssl_cert_file_name
          value: $(tasks.collect-simple-signing-params.results.umb_ssl_cert_file_name)
        - name: umb_ssl_key_file_name
          value: $(tasks.collect-simple-signing-params.results.umb_ssl_key_file_name)
        - name: umb_client_name
          value: $(tasks.collect-simple-signing-params.results.umb_client_name)
        - name: umb_listen_topic
          value: $(tasks.collect-simple-signing-params.results.umb_listen_topic)
        - name: umb_batch_listen_topic
          value: $(tasks.collect-simple-signing-params.results.umb_batch_listen_topic)
        - name: umb_publish_topic
          value: $(tasks.collect-simple-signing-params.results.umb_publish_topic)
        - name: umb_batch_publish_topic
          value: $(tasks.collect-simple-signing-params.results.umb_batch_publish_topic)
        - name: umb_url
          value: $(tasks.collect-simple-signing-params.results.umb_url)
        - name: pyxis_ssl_cert_secret_name
          value: $(tasks.collect-simple-signing-params.results.pyxis_ssl_cert_secret_name)
        - name: pyxis_ssl_cert_file_name
          value: $(tasks.collect-simple-signing-params.results.pyxis_ssl_cert_file_name)
        - name: pyxis_ssl_key_file_name
          value: $(tasks.collect-simple-signing-params.results.pyxis_ssl_key_file_name)
        - name: pyxis_url
          value: $(tasks.collect-simple-signing-params.results.pyxis_url)
        - name: signer_type
          value: $(tasks.collect-simple-signing-params.results.signer_type)
        - name: pyxisServer
          value: $(params.pyxisServer)
      workspaces:
        - name: data
          workspace: pipeline
          subPath: signing
      runAfter:
        - collect-simple-signing-params
